CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS platform_bootstrap (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    installed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO platform_bootstrap (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;
